spring.application.name=BancoLuiz

# URL de conexão (Endereço do cofre)
spring.datasource.url=jdbc:postgresql://localhost:5432/jbank_db

# Usuário padrão do Postgres
spring.datasource.username=postgres

# A senha que você definiu no ALTER USER
spring.datasource.password=1010

# O "Tradutor" (Driver)
spring.datasource.driver-class-name=org.postgresql.Driver

# Oculta as verificações do Spring
logging.level.root=WARN
